name: Run Tests
permissions:
  checks: write
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # noinspection UndefinedAction
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Build with Maven
        run: mvn clean test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/target/surefire-reports/TEST-*.xml'
